# Generated by Django 2.1.7 on 2019-04-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190402_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='listSemana',
        ),
    ]
