# Generated by Django 2.1.7 on 2019-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_delete_listsemana'),
    ]

    operations = [
        migrations.CreateModel(
            name='listSemana',
            fields=[
                ('idsemana', models.IntegerField(primary_key=True, serialize=False)),
                ('semana', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('link', models.TextField()),
            ],
        ),
    ]
