# Generated by Django 2.1.7 on 2019-03-27 22:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0011_auto_20190321_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa_fabrica',
            fields=[
                ('codigo_caixa', models.IntegerField(primary_key=True, serialize=False)),
                ('volume_caixa', models.IntegerField()),
                ('volume_total', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('semana', models.IntegerField()),
                ('rota', models.IntegerField()),
                ('consultora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixa_fb_consultora', to='home.Consultora')),
            ],
        ),
        migrations.CreateModel(
            name='Liberadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('rota', models.IntegerField()),
                ('entregador', models.IntegerField()),
                ('data_liberada', models.DateField(default=datetime.date.today)),
                ('semana_liberada', models.IntegerField(default='201913')),
                ('consultora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberadas_consultora', to='home.Consultora')),
            ],
        ),
    ]
