# Generated by Django 2.1.7 on 2019-03-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190321_1456'),
        ('liberadas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liberadas',
            new_name='Liberada',
        ),
    ]
