# Generated by Django 2.1.7 on 2019-03-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0002_auto_20190327_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa_fabrica',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='caixa_fabrica',
            name='consultora',
        ),
        migrations.RemoveField(
            model_name='caixa_fabrica',
            name='rota',
        ),
        migrations.RemoveField(
            model_name='caixa_fabrica',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='caixa_fabrica',
            name='volume_caixa',
        ),
        migrations.RemoveField(
            model_name='caixa_fabrica',
            name='volume_total',
        ),
    ]
