# Generated by Django 2.1.7 on 2019-03-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0003_auto_20190327_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa_fabrica',
        ),
        migrations.RemoveField(
            model_name='liberada',
            name='semana_liberada',
        ),
    ]
