# Generated by Django 2.1.7 on 2019-03-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0004_auto_20190327_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberada',
            name='semana_liberada',
            field=models.IntegerField(default='201913'),
        ),
    ]
