# Generated by Django 2.1.7 on 2019-03-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0009_auto_20190328_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa_fabrica',
            name='codigo_caixa',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
