# Generated by Django 2.1.7 on 2019-03-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0012_auto_20190328_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberada',
            name='cx_fabrica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caixa_liberada', to='liberadas.Caixa_fabrica'),
        ),
    ]
