# Generated by Django 2.1.7 on 2019-03-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0013_liberada_cx_fabrica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liberada',
            old_name='cx_fabrica',
            new_name='caixa_fabrica',
        ),
    ]
