# Generated by Django 2.1.7 on 2019-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0014_auto_20190329_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberada',
            name='consultora',
            field=models.IntegerField(),
        ),
    ]
