# Generated by Django 2.1.7 on 2019-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0016_auto_20190329_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberada',
            name='volume_atual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liberada',
            name='volume_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
