# Generated by Django 2.1.7 on 2019-03-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0018_auto_20190329_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberada',
            name='caixa_fabrica',
        ),
        migrations.DeleteModel(
            name='Liberada',
        ),
    ]
