# Generated by Django 2.1.7 on 2019-03-29 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0019_auto_20190329_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liberada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultora', models.IntegerField()),
                ('semana', models.IntegerField()),
                ('rota', models.IntegerField()),
                ('volume_total', models.IntegerField()),
                ('volume_atual', models.IntegerField()),
                ('entregador', models.CharField(max_length=50)),
                ('data_liberada', models.DateField(default=datetime.date.today)),
                ('semana_liberada', models.IntegerField(default='201913')),
                ('caixa_fabrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caixa_liberada', to='liberadas.Caixa_fabrica')),
            ],
        ),
    ]
