# Generated by Django 2.1.7 on 2019-03-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberadas', '0020_liberada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberada',
            name='semana_liberada',
            field=models.IntegerField(default=0),
        ),
    ]
