# Generated by Django 2.1.7 on 2019-03-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=15)),
                ('UF', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('codigo_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cidades')),
            ],
        ),
    ]
