# Generated by Django 2.1.7 on 2019-03-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190313_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidades',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
