# Generated by Django 2.1.7 on 2019-03-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190313_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cidades',
            new_name='Cidade',
        ),
        migrations.RenameModel(
            old_name='Distritos',
            new_name='Distrito',
        ),
    ]
