# Generated by Django 2.1.7 on 2019-03-20 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20190320_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultoras',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('codigo_grupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_consultora', models.IntegerField()),
                ('codigo_produto', models.IntegerField()),
                ('numero_nota', models.IntegerField()),
                ('ocorrencia', models.TextField(max_length=200)),
                ('observacao', models.TextField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencias',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
    ]
