# Generated by Django 2.1.7 on 2019-03-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190320_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultoras',
            new_name='Consultora',
        ),
        migrations.RenameModel(
            old_name='Ocorrencias',
            new_name='Ocorrencia',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='Status_type',
        ),
    ]
