# Generated by Django 2.1.7 on 2019-03-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190320_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultora',
            name='codigo_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo'),
        ),
    ]
