# Generated by Django 2.1.7 on 2019-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190320_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='nota',
            field=models.ImageField(blank=True, null=True, upload_to='notas_'),
        ),
    ]
