# Generated by Django 2.1.7 on 2019-03-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ocorrencia_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='codigo_consultora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Consultora'),
        ),
    ]
