# Generated by Django 2.1.7 on 2019-04-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190321_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultora',
            name='codigo_grupo',
        ),
        migrations.AddField(
            model_name='consultora',
            name='CEP',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='bloqueadosn',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='celular',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='ddd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='endcomplemento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='endlogradouro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='endnumero',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='endtlogradouro',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultora_grupo', to='home.Grupo'),
        ),
        migrations.AddField(
            model_name='consultora',
            name='indicante',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='sembaixa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='semlancamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='setor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='telefone1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='telefone2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='tipo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consultora',
            name='ultimativa',
            field=models.IntegerField(null=True),
        ),
    ]
