# Generated by Django 2.1.7 on 2019-04-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190412_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=50)),
            ],
        ),
    ]
