# Generated by Django 2.1.7 on 2019-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultora',
            name='semlancamento',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
