# Generated by Django 2.1.7 on 2019-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190412_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultora',
            name='semlancamento',
            field=models.IntegerField(null=True),
        ),
    ]
