# Generated by Django 2.1.7 on 2019-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190412_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='sembaixa',
            field=models.IntegerField(null=True),
        ),
    ]
