# Generated by Django 2.1.7 on 2019-04-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190412_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupomae',
            field=models.IntegerField(null=True),
        ),
    ]
