# Generated by Django 2.1.7 on 2019-04-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190412_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidades',
            name='cep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cidades',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cidades',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
