# Generated by Django 2.1.7 on 2019-04-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190412_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultora',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultora_cidade', to='home.Cidades'),
        ),
    ]
