# Generated by Django 2.1.7 on 2019-04-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190412_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_type',
        ),
    ]
