# Generated by Django 2.1.7 on 2019-04-30 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0026_delete_status_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.IntegerField()),
                ('numero_nota', models.IntegerField()),
                ('observacao', models.TextField()),
                ('nota', models.FileField(blank=True, null=True, upload_to='ocorrencias/notas')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('last_updated', models.DateField(auto_now=True)),
                ('garantia', models.BooleanField(default=False)),
                ('nomeProduto', models.CharField(max_length=100, null=True)),
                ('semanaNota', models.IntegerField(default=0)),
                ('consultora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_consultora', to='home.Consultora')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia_tipo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status_type',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.Ocorrencia_tipo'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.Status_type'),
        ),
    ]
