# Generated by Django 2.1.7 on 2019-03-21 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0011_auto_20190321_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.IntegerField()),
                ('numero_nota', models.IntegerField()),
                ('ocorrencia', models.TextField(max_length=200)),
                ('observacao', models.TextField()),
                ('nota', models.ImageField(blank=True, null=True, upload_to='ocorrencias/notas')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('last_updated', models.DateField(auto_now=True)),
                ('codigo_consultora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Consultora')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Status_type')),
            ],
        ),
    ]
