# Generated by Django 2.1.7 on 2019-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='semanaNota',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
