# Generated by Django 2.1.7 on 2019-03-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_auto_20190326_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='nota',
            field=models.FileField(blank=True, null=True, upload_to='ocorrencias/notas'),
        ),
    ]
