# Generated by Django 2.1.7 on 2019-03-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_auto_20190327_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='consultora',
            field=models.IntegerField(),
        ),
    ]
