# Generated by Django 2.1.7 on 2019-03-28 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_auto_20190327_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='consultora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_consultora', to='home.Consultora'),
        ),
    ]
