# Generated by Django 2.1.7 on 2019-04-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0006_auto_20190327_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='nota',
            field=models.ImageField(blank=True, null=True, upload_to='ocorrencias/notas'),
        ),
    ]
