# Generated by Django 2.1.7 on 2019-04-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0007_auto_20190413_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='nota',
            field=models.FileField(blank=True, null=True, upload_to='ocorrencias/notas'),
        ),
    ]
