# Generated by Django 2.1.7 on 2019-04-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0008_auto_20190413_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='garantia',
            field=models.BooleanField(default=False),
        ),
    ]
