# Generated by Django 2.1.7 on 2019-04-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0009_ocorrencia_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='garantia',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
