# Generated by Django 2.1.7 on 2019-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0010_auto_20190425_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='garantia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
