# Generated by Django 2.1.7 on 2019-04-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0011_auto_20190425_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia_tipo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status_type',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='ocorrencia',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='garantia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.Status_type'),
        ),
    ]
