# Generated by Django 2.1.7 on 2019-04-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0012_auto_20190429_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.Ocorrencia_tipo'),
        ),
    ]
