# Generated by Django 2.1.7 on 2019-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0013_ocorrencia_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='nomeProduto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
