# Generated by Django 2.1.7 on 2019-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0014_ocorrencia_nomeproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='semanaNota',
            field=models.IntegerField(default=0),
        ),
    ]
